### ISSUE TITLE
Spy heads are naked?

### ISSUE THREAD

**Issue by chamiy** [Fiore-Free/Mange_CBO_Community_Patch#3]
Seems like the civilian spy head of the game would be naked, wearing only a twisted cloak

（Issue resolved, just don't enable CFP...）

**Comment by Fiore-Free** [comment]
Sounds like a conflict with another mod in your list what other mods are you running?

**Comment by chamiy** [comment]
Ok, I found out that what is causing the character to be naked is Stop Leg Shrink. but even using only the must-have mods: cfp, cbo, and this patch, it still produces twisted capes, all of them from cfp!
